### PR TITLE
Extracting epw year data from .epw files.

### PR DESCRIPTION
**Pull request by stgeorges**
Hi @chriswmackey , @mostaphaRoudsari ,

I am working on a new component which has to use the epw year data from .epw file. I made a commit to the current "epwDataReader" method from ladybug_ladybug.py file. Months, days and hours are extracted too, but I am mainly concerned about the epw year data, as this one can not be predicted. Months, days and hours can.
Would changing of "epwDataReader" disturb the current overall code in any way, other than having to make changes to the "Ladybug_Import epw" component code?

Thank you for the reply.

### CODE REVIEW

**Comment by chriswmackey** [comment]
@stgeorges ,
This is going to have some repercussions on my comfort map workflow as well as the importEPW component (both rely on this function to parse an epw file).  Writing this function so that the days/month/year outputs are returned after the other outputs should ensure that these other components are not disturbed.  Would this be ok?
-Chris

**Comment by stgeorges** [comment]
Hi @chriswmackey.
Thanks for the reply. 
Just to check if I understood you right.
So basically, instead of this:
```
# line 887 in epwDataReader method
return epwYear, epwMonth, epwDay, epwHr, dbTemp, dewPoint, RH, windSpeed, windDir, dirRad, difRad, glbRad, dirIll, difIll, glbIll, cloudCov, rainDepth, barPress
```
To have this:
```
# line 887 in epwDataReader method
return dbTemp, dewPoint, RH, windSpeed, windDir, dirRad, difRad, glbRad, dirIll, difIll, glbIll, cloudCov, rainDepth, barPress, epwYear, epwMonth, epwDay, epwHr
```
Did I get that right?

**Comment by mostaphaRoudsari** [comment]
Hi @stgeorges and @chriswmackey- Yes. if you move them to the end then we should be fine.

**Comment by stgeorges** [comment]
Hi @chriswmackey , @mostaphaRoudsari ,

I renamed epwYear, epwMonth, epwDay, epwHr to modelYear, modelMonth, modelDay, modelHr.
In the end I think it's much better if only "modelYear" should be added to the "epwDataReader" method, as the rest three ones are always constant.

Here is the edited ladybug_ladybug.ghuser file too:
http://www.filedropper.com/ladybugladybug

I also made an edit to the "Import epw" component, so that new "modelYear" output gets added. Here is the "import epw.ghuser" file too:
http://www.filedropper.com/ladybugimportepw

Thank you.

**Comment by mostaphaRoudsari** [comment]
@stgeorges thanks for making the changes. Why do you think modelYear is going to be useful for users? I find it usually really confusing for people to know that weather file is combined from different years and I rather not to expose it. Do you have a good use case that you think we should add it as one of the outputs?

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari ,
The component I am developing depends on the model year, whether it's leap year or not.
Why would exposing "modelYear" and the fact that epw weather data for each/several month was gathered from different years be such a confusing thing? There's a docstring (explanation) for "modelYear" ouput, saying what it is.

**Comment by mostaphaRoudsari** [comment]
@stgeorges if it helps with your development then let's merge it. Dru and Linda are actually in the process of adding some new weather files to epwmap which are using more recent weather data and it might be a good idea to have this feature. @chriswmackey can you check the explanation and see if it passes your description writing standards?

**Comment by stgeorges** [comment]
@mostaphaRoudsari , Thank you.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @stgeorges ,

I looked at the description and added a bit more to help ensure that users do not get confused.  Here is the new one:

modelYear: The year from which the hourly data has been extracted. EPW files are synthesized from real recorded data from different years in a given climate. This is done to ensure that, for each month, the selected data is statistically representative of the average monthly conditions over the 18+ years of recording the data. Different EPW files will be synthesized from different years depeding on whether they are TMY (Typical Meteorological Year), TMY2, TMY3, AMY (Actual Meteorological Year) or other.

I agree that having this data will be very useful.
-Chris

**Comment by stgeorges** [comment]
Nice one @chriswmackey . Thanks.

**Pull request merged**
