### PR TITLE
False Start Toggle

### PR DESCRIPTION
**Pull request by AndrewHeumann**
Adding a special toggle object that always reverts to "False" on file open to avoid accidentally triggering simulations on launch.

### CODE REVIEW

**Comment by devngc** [comment]
@AndrewHeumann,
That would be really useful. Thanks a lot!

**Comment by mostaphaRoudsari** [comment]
Thanks @AndrewHeumann! Merged!

**Comment by Vyrwn** [comment]
that would be so good. Thanks @AndrewHeumann

**Comment by chriswmackey** [comment]
Thank you @AndrewHeumann !!! Very useful indeed!

**Pull request merged**
