### PR TITLE
Added ability in Ladybug_Legend Parameter to specify custom colors for high and low bound 

### PR DESCRIPTION
**Pull request by antonszilasi**
Very handy for LEED daylight analysis

### CODE REVIEW

**Comment by chriswmackey** [comment]
@antonszilasi ,
I am not going to be able to merge this because it is adding something to legend parameters that is not going through the main LB_LB function that processes LegendPar and allows LegendPar to be applicable to many components.  As a result, it would break legendParameters on all of the components except for recolor mesh.  I am also not so sure why these extra inputs are needed.  Connecting up 2 colors to customColors already allows you to set a high bound color and a low bound color.  Adding redundant inputs like this seems a bit inelegant and reminds me of some other software that will have, say, 6 different locations to do the same command.
-Chris

**Comment by antonszilasi** [comment]
@chriswmackey 

I guess I didn't explain it clearly enough currently connecting 2 colors does allow you set a high and low bound color but you still see shades in between, see below

capture 3
capture 4

**Comment by antonszilasi** [comment]
@chriswmackey  as per our discussion I will add this to recolor mesh component

**Comment by chriswmackey** [comment]
Sounds good @antonszilasi !

**Pull request closed without merging**
