### PR TITLE
Polished groundtemp component updated ladybugladybug

### PR DESCRIPTION
**Pull request by antonszilasi**

### CODE REVIEW

**Comment by chriswmackey** [comment]
@antonszilasi ,
This pull request is absolutely stellar.  I am going to merge it in now.
Also, I changed the default ground temperatures going into the E+ runs to no longer be just 18C but to be informed by the undisturbed ground temperatures using your code here.  I will make sure that your new code is compatible with this shortly.
-Chris

**Comment by chriswmackey** [comment]
@antonszilasi ,

I took a closer look at the changes that you made after I merged it and realized that you edited the function that brings in all of the data other than the ground temp from the EPW file.  You removed the the key at the top of the header.  I had to go back and fix it but I was wondering why you had made this change.

-Chris

**Comment by mostaphaRoudsari** [comment]
Thank you both! I have to find some time to catch up with all the new developments that you guys are doing. Do you have a coming workshop that I can attend? ;)

**Comment by antonszilasi** [comment]
@chriswmackey  I'm not quite sure what you mean by your last comment, yes I changed the function depthData so that the ground temp component would output temperature at depth 2 instead of just 2 e.g it removed a line from the output

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
It is true that Anton is rocking it!  He's ascending the learning curve quickly and I think that I need to get caught up too.  Perhaps we can do some type of webinar/skype-based catch-up session in the near future.

@antonszilasi ,
I was talking about this change that you made in the pull request:
https://github.com/antonszilasi/ladybug/commit/3f5304c4d0746e0db460c58b3ef95c5c70f1a27b#diff-b9af826a74ec3aa0ea71038078755d9cL844
you took out the self.strToBeFound and this caused many of the components to stop working.  I was just wondering how this change happened so that we can avoid changes that break the other components in the future.

-Chris

**Pull request merged**
