### PR TITLE
fixing the bug with scaling with Feet units

### PR DESCRIPTION
**Pull request by stgeorges**
@chriswmackey , @mostaphaRoudsari ,

Can this pull request be merged, please.

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@stgeorges this PR has conflicts. Can you resolve the conflicts and send a new PR?

**Comment by stgeorges** [comment]
This is the issue. For some reason I can not merge the updates which you made yesterday (merged my #271 pull request and added the corresponding .ghuser file.
I do not understand why is that.
I will delete the whole repository and try to send a new pull request.

**Comment by stgeorges** [comment]
@mostaphaRoudsari 
You can close this pull request. I deleted the whole repository, forked it and created a new pull request:
https://github.com/mostaphaRoudsari/ladybug/pull/273

**Comment by mostaphaRoudsari** [comment]
Thanks! I merged the other one. I'm closing this.

**Pull request closed without merging**
