### PR TITLE
Avoiding Div/0 in MeshSelector

### PR DESCRIPTION
**Pull request by hwoehrle**
Avoiding Div/0 when none of the TestPoints meet the levelOfPerformance. This is necessary because otherwise the script stops and doesn't evaluate further resultets

### CODE REVIEW

**Comment by hwoehrle** [comment]
Sorry, i'm using github for the first time and of course started editing the wrong lines. Just ignore the older commits

**Comment by devngc** [comment]
Thanks  for addressing this

**Comment by chriswmackey** [comment]
Thanks for fixing this, @hwoehrle .  And no worries about sending multiple commits (we can squash them all into one when we merge them). 

Your changes look good but one small edit that would be good to have before we merge it is if you can change [the date on the component](https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Mesh%20Threshold%20Selector.py#L51) to today's date.  If you send us another commit with the date changed, I'll merge this in.

**Comment by hwoehrle** [comment]
this time with changed date of the component

**Comment by chriswmackey** [comment]
@hwoehrle ,

It looks like you overwrote the code change that you were adding when you pushed this commit.  Make sure that the component you are exporting has both the change for div/0 as well as the date change and then it all should be good.

**Comment by hwoehrle** [comment]
Ok, i'm stumbling to the finish line ;-)

**Comment by chriswmackey** [comment]
Looks excellent @hwoehrle !  Merged!

**Comment by chriswmackey** [comment]
Welcome to the [contributor's page](https://github.com/mostaphaRoudsari/ladybug/graphs/contributors) @hwoehrle !

**Pull request merged**
