### PR TITLE
Text2Mesh

### PR DESCRIPTION
**Pull request by MingboPeng**
Text2Mesh

### CODE REVIEW

**Comment by chriswmackey** [comment]
@mingbopeng ,
Thank you very much for the commit but I am a bit unclear on the purpose of the component and there is no header or description in the code to tell me this. Why not use the native GH "TextTag3D" component to accomplish the same thing with more control over variables?
-Chris

**Comment by MingboPeng** [comment]
@chriswmackey  Hi Chris, the native GH TextTag3D has a problem with captureView, because the TextTag3D executed after captureView. Making text to mesh, then get the length of list to trigger captureView is the only way that I can find to solve this problem for a parametric study with some user's text note. This is just using the function that is existed in Ladybug already, and made it stand alone.

**Comment by chriswmackey** [comment]
@MingboPeng ,

There is a better way to get the TextTag3D to execute before the captureview.  The order of execution of the components can be changed by moving components you want to execute last to the front of the canvass (select the components and hit Cntrl+F) or moving the components you want to execute first to the back of the canvas (select the components and hit Cntrl+B).

-Chris

**Comment by MingboPeng** [comment]
@chriswmackey 
Hi Chris, awesome, I didn't know this trick. Thanks for letting me know;>

**Comment by chriswmackey** [comment]
@mingboPeng . Glad to hear that it solved the issue.  Given that we have have determined this component is essentially the same as the text tag 3d, I am going to close out the pull request. Feel free to reopen/resend if I am missing something.

**Pull request closed without merging**
