### PR TITLE
Output Description Added

### PR DESCRIPTION
**Pull request by devngc**
Forgot to add the description for outputs that one sees while hovering over the output. The descriptions are added for both the new outputs.

### CODE REVIEW

**Comment by devngc** [comment]
Frequency displayed on wind rose. Display on/off through boolean.

**Comment by devngc** [comment]
1. User input added for frequency display
02a
2. Text alignment and justification improved
01a

**Comment by mostaphaRoudsari** [comment]
@devngc sorry for the delay. The changes looks good, but there ia conflict in your PR. Can you solve the conflict and send a new pull request?

**Comment by devngc** [comment]
@mostaphaRoudsari , separate pull request has been made to avoid merging conflict. I think we can close this pull request.

**Comment by mostaphaRoudsari** [comment]
Thanks. Merged!

**Pull request closed without merging**
