### PR TITLE
New Features in Wind Rose + Ladybug_Beaufort Ranges

### PR DESCRIPTION
**Pull request by devngc**
This PR contains recently added features to the wind rose component.

Also, a new component named Ladybug_Beaufort Ranges is added.

### CODE REVIEW

**Comment by devngc** [comment]
This PR addresses #328 and #327 both.

**Comment by chriswmackey** [comment]
@devngc ,
This looks great!
Merged!

**Comment by devngc** [comment]
I really wanted to add these features before the workshop on 8th. I thank @ayezioro, @chriswmackey, and @mostaphaRoudsari for your time, inputs, reviews, and help.
Sincerely,
-Devang

**Comment by chriswmackey** [comment]
@devngc ,
Of course!  Thank you so much for these great additions to the project!

**Pull request merged**
