### PR TITLE
Fixing the "(0.0.63) "0.0.64" version and "2013 to (2016) 2017" mistake

### PR DESCRIPTION
**Pull request by stgeorges**
Hi @chriswmackey , @mostaphaRoudsari ,

I forgot to change the version and year in the last pull request:
https://github.com/mostaphaRoudsari/ladybug/pull/352

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@stgeorges you're missing `ladybug_ladybug.py` and also the updated userobjects with the new dates!

**Comment by stgeorges** [comment]
@mostaphaRoudsari , Isn't ```ladybug_ladybug.py``` ok (version is correct: 0.0.64, and the date: 2013-2017) in the https://github.com/mostaphaRoudsari/ladybug/pull/352 pull request? And its userobject (Ladybug_Ladybug.ghuser)?

Is something wrong with ```Ladybug_Body Characteristics.ghuser``` and ```Ladybug_Thermal Comfort Indices.ghuser``` objects?

**Comment by mostaphaRoudsari** [comment]
You're right about `ladybug_ladybug.py` component.

The UserObjects are created by the wrong version. You need to recreate them with the new code. Is that make sense?

**Comment by stgeorges** [comment]
Hm, but I did that.
[This commit](https://github.com/mostaphaRoudsari/ladybug/pull/353/commits/e11f148fced5d29a18953c35836586a072d3b97a):

github1

github2

has both version (0.0.64) and date (2013-2017) issues fixed with ```Ladybug_Body Characteristics.ghuser``` and ```Ladybug_Thermal Comfort Indices.ghuser```.

At your place, these changes can not be seen?

**Comment by mostaphaRoudsari** [comment]
Hmmm... I see. I'm not sure why they don't show up in the final files changed: https://github.com/mostaphaRoudsari/ladybug/pull/353/files

I'll merge this and we can get it fixed from our side if it didn't show up correctly.

**Comment by stgeorges** [comment]
Okay. Sorry for all the mess caused by me.

**Comment by mostaphaRoudsari** [comment]
All good! Thanks for the PR. 👍

**Comment by chriswmackey** [comment]
Awesome.  Glad that we got this merged in and thank you so much for including this option @stgeorges .

**Pull request merged**
