### PR TITLE
Average wind velocities Added

### PR DESCRIPTION
**Pull request by devngc**
Average wind velocities are displayed on wind rose for all directions

### CODE REVIEW

**Comment by devngc** [comment]
Hi @mostaphaRoudsari,

This PR is created in reference to #256 . Following are some images that show this implementation;

Regular Display of Average Wind Velocities on Wind Rose. Display on / off controlled through boolean. Option provided to change radial offset of texts displaying average wind velocity.
average wind velocities_top

Now Analysis Period is applied (July 21 - August 21) We are looking at Boston-Logan.Intl.AP.725090_TMY3/all
analysis period applied_top

Now conditional statement is applied (a > 10)
conditional statement applied_top

If input is provided to annualHourlyData_ then these values are displayed on the other wind rose as well.

**Comment by mostaphaRoudsari** [comment]
Amazing! Thanks @devngc for picking this issue up and implement it. Much appreciated!

**Comment by mostaphaRoudsari** [comment]
@devngc a minor comment for the next PRs. Make sure to update the date of the component before creating the userobject. That will be very helpful for debugging if any issues come up later.

**Comment by ayezioro** [comment]
hi @devngc ,
Thanks for this. I have though a new challenge for you, unless you tell this is doable:
There are some requirements regarding % of time that you can allow for considering the wind as usable and/or dangerous. For instance, for mechanical reasons, annual average beyond 1% at (say) 20 m/s is considered dangerous and as such you have to address the issue. There are different requirements for different velocities, as i said, some are related to the mechanical influence of the wind and others for comfort reasons.
You think it is doable here if you already get the averages?
Thanks,
-A.

**Comment by devngc** [comment]
Hi @ayezioro,

Your comments make me instantly think of the Beaufort scale. Following is what beaufort scale says about wind velocity near to 20 m/s. “Very strong storm, smaller trees can be uprooted, roof tiles blow off, buildings are damaged”. This scale is basically a table of observable effects of the wind on our surrounding. Do you mean such effects of wind velocity when you say, “mechanical influence of the wind?”

For the thermal comfort, sure, there’s physiological cooling effect on the skin due to the wind. But then those effects also depend on the air temperature (for outside) or M.R.T. (for inside) right. And I believe the same are greatly covered by Chris in comfort models. I am not sure what information we can give on the wind rose for its influence on thermal comfort. Please feel free to educate me here.

I find your thought interesting and would love to work on adding more information to the wind rose. Thank you for sharing your thoughts with us and getting me involved. I appreciate that.

Finally to respond to your question. I would really like to know more about what you have in mind. But my instincts tell me, this should be doable.

Thanks,
Devang

**Comment by devngc** [comment]
Hi @mostaphaRoudsari,
Sure. I was under impression that only you and Chris control that, so never bothered to change it. Now that it's clear, will do from next time. Thanks for pointing that out.
-Devang

**Comment by ayezioro** [comment]
Hi @devngc,
Yes. What i have in mind is the Beafourt scale as presented by the BRE document (for both comfort and mechanical). They relate to the comfort regardless other factors and i like it as kind of rule of thumb. I'll be happy if the component can provide the possibility of getting the frequency as a conditional statement (as in the sunPath for example, say a>20 for frequencies greater than 20 m/s).
Those are the links for the BRE report, just in case you don't have them:
https://www.dropbox.com/s/uxycyrna7e7ziix/BRE-TB-Recomms_01.jpg?dl=0
https://www.dropbox.com/s/j57fi4gviv0gtjn/BRE-TB-Recomms_06.jpg?dl=0
Thanks,
-A.

**Comment by devngc** [comment]
Hi @ayezioro,
I have read your last comment and thank you for providing references, they're helpful. I have better understanding of your idea than last time now. There will be some time before I get back to you with a sample / more questions. I hope this is not very urgent.
Thanks,
-Devang

**Comment by ayezioro** [comment]
Hi @devngc,
No problem. Not urgent, just a wish ... auseful one.
-A.

**Comment by devngc** [comment]
@ayezioro,

I originally planned to work on this after 20 Dec. but @mostaphaRoudsari gave me a good dose of inspiration yesterday, so I have something to show today. I will be very happy to hear thoughts of both of you.

In response to your wish and comments, I have made a few enhancements to the wind rose component. Following is a pre-view of enhancements


I made a new component named "Ladybug_Beaufort Ranges". This component has all the beaufort ranges that one can supply to conditionalStatement_ input of the wind rose component.

This is where I propose the component shall live
beaufort ranges 01

It is a very simple drop-down list. And it outputs beaufort ranges.
beaufort ranges 02

Let's look at some roses now;

1. Classic wind rose
classic wind rose


2. Ladybug_beaufort Ranges applied (Moderate Breeze selected) Please take note of statement added in the bottom.
beaufort applied

3. Beaufort + Average wind velocities
beaufort average velocities

4. Beaufort + Average wind velocities + Analysis Period Applied
beaufort average velocities analysis period

5. Beaufort + Frequencies
beaufort frequencies

6. Ladybug_Beaufort Ranges is now disconnected and regular conditional statement is connected. Please make note of number next to average wind velocities and notes added at the bottom.
normal conditional average velocities 01

7. Regular conditional Statement another variation
normal conditional average velocities 02

8. Regular conditional statement statement + analysis period
normal conditional average velocities analysis period

Thank you for your time.
-Devang

**Comment by ayezioro** [comment]
Hi @devngc,
Seems to be that you answer to all my requests here. Very nice!!
Didn't test the sample file but from the above images i'm completely satisfied.
Thanks a lot,
-A.
P.S. Mostapha is always a good source of inspiration

**Comment by devngc** [comment]
@ayezioro,
Thank you! I am happy this addresses your wish. I am happy how we converged on the beaufort scale by coincidence. I thought of making a new component on that line, but I am happy that we added to the original component. Thank you for all your inputs and time. I enjoyed this collaboration. 

@mostaphaRoudsari,
I will wait for your comments before making a PR.

Regards,
-Devang

**Comment by ayezioro** [comment]
Hi @devngc,
Testing the sample. There are fatal errors with it when i choose "Strong Gale" or "Strong Breeze". Debugging it says:

> Runtime error (ValueErrorException): step must not equal 0
> Traceback:
> 
>   line 338, in fxrange, "C:\Users\Abraham\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\Iron
> Python
> (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rhinoscript\utility.py"
>
>    line 354, in frange, "C:\Users\Abraham\AppData\Roaming\McNeel\Rhinoceros\5.0\Plug-ins\IronPython (814d908a-e25c-493d-97e9-ee3861957f49)\settings\lib\rhinoscript\utility.py"
>   line 537, in main, "<string>"
>   line 996, in script
> 

I assume some exceptions occur there (max and min Freq are equal 0).
Thanks,
-A.

**Comment by devngc** [comment]
@ayezioro,
Thanks for checking and reporting. I faced that error as well. It occurs when no hour meets the conditional statement. @mostaphaRoudsari  has already provided a warning if this happens. I will find out why the component skips the warning and reports an error in certain cases.
Thanks,
-Devang

**Comment by devngc** [comment]
@ayezioro,
I fixed that. The component will issue a warning instead of throwing error.
Thanks,
-Devang

**Comment by ayezioro** [comment]
Great @devngc!!
Thank you,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi @devngc and @ayezioro! That was quick. Thank you both. It looks great, and I think this is a very smart approach to add on top of the current development instead of creating a new component.

I should have commented on this thread sooner but it's always better to open a new issue for cases such as this. It will be quite hard to find this discussion in a couple of month.

I have two comments and one question:

1. Will the component also work if user changes the wind speed units to mph?
2. Can we change 'In this wind' to 'At this wind speed'.
3. Can we wrap the text so it does stay inside the width of the wind-rose itself?

**Comment by devngc** [comment]
@mostaphaRoudsari,

Thanks for your comments. Please find my responses to your comments below.

> Will the component also work if user changes the wind speed units to mph?

Yes. I have added Beaufort ranges in miles per hour to Ladybug_Beaufort Ranges component.

ladybug_beaufort ranges


> Can we change 'In this wind' to 'At this wind speed'.

I have revised all the notes. Now it says, "At this speed". Please let me know if this doesn't work for you.
> Can we wrap the text so it does stay inside the width of the wind-rose itself?

Complied.


Following image shows wind roses with m/s and m/h side by side
mps and mph

Sample file can be fund [here.](https://github.com/devngc/Work-in-Progress/blob/master/WindRose.gh)

Please let me know should you have more comments. I am ready to push this through a PR.

Thanks,
-Devang

**Comment by ayezioro** [comment]
Hi @devngc,
Good to go for me.
But i have some questions though:
If i want to have the outputs in MPH but i don't input the Beafourt scales it is possible? If don't it will be useful, and if so, having both scales in the ValueList component is unnecessary.
Usually the wind data will be in m/s (from epw file), so it is hard to think about cases where mph will be in the input, but just in the output. If you agree i suggest having a boolean for the output units, instead of duplicating the value list.
Makes sense?
Thanks,
-A.

**Comment by devngc** [comment]
@ayezioro,

Thank you commenting.

In case you don't connect Beaufort scale. The component will still work. You will have average velocities displayed for all direction. However, if you do this, you will not have following;
 1. Those Beaufort numbers displayed along with average velocities
 2. Summary displayed at the bottom.

The Beaufort ranges in miles per hour are not exact conversion from m/s. I have taken them from wikipedia page for the beaufort scale. So, I am of the opinion that we should keep ranges in m/s and mph.

The component that supplies the Beaufort ranges is a simple drop down list. So I don't know if I can output different values based on boolean input. Here also, I would like to keep a simple drop down list rather than making a separate python component.

Thanks,
-Devang

**Comment by devngc** [comment]
@ayezioro,
I am also adding a warning in case the user has winds speed in m/s and selects a Beaufort range in mph and visa-versa.
-Devang

**Comment by chriswmackey** [comment]
@devngc ,

Sorry for being so late to the party here.  I just wanted to say that this is wonderful and average wind speeds are definitely something that we need for better integration with Butterfly.    With this CFD application in mind, I have a couple of requests:

1) I am not sure why the component outputs the wind speeds and directions when the user already has this information  (they are the inputs to the component).  I guess that we had this before your edits, @devngc , but I realize that it really doesn't make sense.  Instead of this redundancy, it would be really nice to have the average wind velocities and total frequency output as a list of numbers that correspond to the number of directions around the wind rose.  This will make it easier to integrate the average speeds in the setup of multiple CFD simulations form multiple directions.

2) I noticed that you do not get average wind velocities or frequencies when you specify a number of directions that is different than the default:
windrose36
This is very problematic for a CFD application as you won't usually be running 16 CDF studies.  I see that the reason why we don't have the average speeds for different directions seems to be that you [hard-coded this](https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Wind%20Rose.py#L676-L727) and it would be really nice if you re-wrote this function to be felxible for a number of directions.

3) I think the offset variables don't need to be exposed as inputs on the component.  I see that you put them in there so that the user can display both frequency and speed without them being on top of each other but I feel that pretty much everyone will want this done automatically for them.
windroseoverlap


-Chris

**Comment by devngc** [comment]
Welcome! @chriswmackey,

The windSpeeds and windDirections outputs provide wind speeds and wind directions for the wind rose that is being displayed.  But I agree that we can do away with them.

I am in agreement with your comments. However, just to be sure. I will summarize them.

1. Remove windSpeeds and windDirections outputs. Instead, provide average wind velocities and frequencies as lists for all directions.
2. Produce wind velocities and frequencies for all acceptable directions.
3. Keep offset for average velocities and frequencies permanent and remove offset inputs for wind velocities and frequencies.

Thank you for taking time and providing this feedback.
-Devang

**Comment by chriswmackey** [comment]
Ahhhhh, that's right. I was so into the CFD applications of the wind rose that I forgot about the conditional statement/analysis period. Keeping the windSpeed and windDirections sounds good, then. It would just be nice to organize the outputs into data outputs (windSpeed, windDirections, avgWindSpeed, avgFrequencies, windRoseDirections) and visual outputs (windRoseMesh, windRoseCurves, legend, etc.).

Thanks again @devngc . This is all very useful!
-Chris

**Comment by ayezioro** [comment]
@devngc,
I meant to have a boolean in the windRose component and not in the list. In this way you save duplicating the list. This also can enable having mph output without giving the beaufort list. Of course it means changing the windRose component code with a series of IF, ELIF statements, whie the list will give only an index for each option.
Anyway, this looks great and is very useful.
Thanks again,
-A.

**Comment by devngc** [comment]
@ayezioro,

> whie the list will give only an index for each option.

This is brilliant! I very much like this idea. This will make things much easier for me.

I am still not sure what you mean when you say 

> mph output without giving the beaufort list.

We have average velocities even if we don't connect  the Beaufort list. I would really like to understand your requirement here. Can you elaborate what do you mean by "mph output" please?

Thanks,
-Devang

**Comment by ayezioro** [comment]
i think the windRose can't give the results in mph (i'm not 100% sure, and can't check right now). The only way i see is giving your list in beaufort mph. Am i right?
So, if what i say is true, and assuming there are people that will like to get the roses in mph WITHOUT inputting the list value, but just from choosing from a boolean option in the windRose component.
If there is already the option so that's good and you can forget what i'm asking.
Hope it is clear(er) now.
Thanks again,
-A.

**Comment by devngc** [comment]
@ayezioro,

Wind Rose component gives results in mph since circa 2013 if I'm not wrong. @mostaphaRoudsari  envisaged this since the beginning and made necessary implementations. There's a component named Ladybug_ms2mph. That takes wind speeds from import EPW and provides wind speeds in mph.

Regards,
-Devang

**Comment by ayezioro** [comment]
Perfect @devngc!
This is not something i need for myself. I'm happy with m/s :-)
-A.

**Comment by chriswmackey** [comment]
@devngc ,

I have found an issue that is more pressing than my previous suggestions but is related to my comment about the way that you calculate average wind speed.  It seems that your edits have broken the ability to use an analysisPeriod with the wind rose, which will severely limit it's application in certain files:
windrosebug

You can find a GH file that replicates the error here:
https://www.dropbox.com/s/f30jajk4mm63gli/NewWindRoseBug.gh?dl=0

Please send an updated pull request that restores this feature soon.  Otherwise, we may have to revert the changes until you have a fully-functional component.

Thank you,
-Chris

**Comment by devngc** [comment]
@chriswmackey,
Thanks for pointing that out.
I am aware of that one and I have addressed that already on the version I am currently working on.
Please check revised file [here.](https://github.com/devngc/Work-in-Progress/blob/master/NewWindRoseBug.gh) I have patched a few lines.
Thanks,
-Devang

**Comment by mostaphaRoudsari** [comment]
I opened a new issue for this conversation and am going to lock this one! https://github.com/mostaphaRoudsari/ladybug/issues/327

**Comment by chriswmackey** [comment]
@devngc ,
Ok.  I don't think there's any more need to discuss the analysisPeriod issue, then.  Just please send the new pull request soon even if all of the other features are not in yet.  I would rather us do two pull requests (one to fix the bug and another later one to add in new features) unless you think that you can get all new features within a day or similar time frame.

I have opened an issue for the features that I have requested here so that we do not confuse them with the Beaufort features:
https://github.com/mostaphaRoudsari/ladybug/issues/328

-Chris

**Pull request merged**
