### PR TITLE
 fixed default folder check

### PR DESCRIPTION
**Pull request by MingboPeng**

### CODE REVIEW

**Comment by chriswmackey** [comment]
@MingboPeng ,
You can see @mostaphaRoudsari 's and my full thoughts on this at the Honeybee Repo.  There are two other F_OKs in Ladybug_Ladybug that we wanted to change over that are for setting default folders on Mac.  So I committed the changes here:
https://github.com/mostaphaRoudsari/ladybug/commit/bdcb0710253740b5099f81a139aed19729227d78
and I'm going to close out this PR.
Thanks again!

**Comment by chriswmackey** [comment]
@MingboPeng ,
Soon after making this change, I realized that it seems to have created a bug.  Namely, weather files cannot be downloaded to c:\ladybug  
image
As such, I think that I am going to have to revert it for now and we'll just have to investigate later.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, the error doesn't seem to have anything to do with changes made by @MingboPeng in this PR. See this: https://www.codeproject.com/Questions/752653/Too-many-automatic-redirections-were-attempted

**Comment by chriswmackey** [comment]
@mostapharoudsari ,
I can say without a doubt that reverting this commit stopped the error from happening. I will admit that I cannot explain why this is the case since, as.you say, the error seems unrelated. Until I can figure it out, I am going to leave it reverted.

**Comment by MingboPeng** [comment]
@chriswmackey  I cannot recreate this problem. It seems working on my computer.
image

**Pull request closed without merging**
