### PR TITLE
Changing the sky view factor and radiation

### PR DESCRIPTION
**Pull request by stgeorges**
Adapting the previous skyViewFactor output to the _"[discussion] Sky View Factor"_ topic from [grasshopper forum](http://www.grasshopper3d.com/group/ladybug/forum/topics/discussion-sky-view-factor).
Adding cloudiness factor to the atmospheric long-wave radiation.

Here are the .ghuser files:
http://www.filedropper.com/21may2016

Thank you.

### CODE REVIEW

**Comment by chriswmackey** [comment]
@stgeorges ,

Thank you for adding this in and all looks good so I will merge it in now.  I have always been a bit skeptical of total sky cover in EPW files as many of the values were recorded fairly qualitatively as I understand it.  Still, if you have concluded that this improves the accuracy of the long wave radiation calculation, I will put the same method into the comfort maps and the solar-adjusted temperature component.

-Chris

**Comment by chriswmackey** [comment]
Created an issue for myself:
https://github.com/mostaphaRoudsari/ladybug/issues/261

**Comment by stgeorges** [comment]
Hi @chriswmackey ,

Thank you for the quick merge.
I agree with you: to my knowledge skyCover data obtained from the weahter stations is a visual estimate. It can also be calculated, as

> N = (1-Kglob/Kglob_clearSky)*10 # in tens

the ratio of the measured globalHorizontalRadiation to the theoretical globalHorizontalRadiation under clear sky conditions. But this method is only applicable during daytime.

**Comment by chriswmackey** [comment]
@stgeorges ,
Thanks for posting the formula for sky cover from global radiation.  I worry that the formula does not account for the case where you have a lot of cloud cover around the location of the sun but not much in the rest of the sky (or vice versa) and I am actually leaning more towards the qualitative EPW method now.  In any case, the literature that you posted on the GH forum about the empirical validation of sky temperature calculations definitely makes me feel more comfortable about using this method.  I'll work it into the other components shortly.
Thanks again!
-Chris

**Comment by stgeorges** [comment]
Hi @chriswmackey ,

Thank you for the kind words.
I guess every method has it's downsides. Also the upper skyCover from Kglob can not be used in this case, as we need to know the skyCover during the night too.
I added the explanation about the new pull request in the Mean radiant temperature topic [on grasshopper forum](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1537960).

**Comment by chriswmackey** [comment]
@stgeorges ,
I have posted a response on that same GH discussion.  I think I may have found a better method than either the Kglob or the sky cover.

**Pull request merged**
