### PR TITLE
Change group & Bug solving

### PR DESCRIPTION
**Pull request by ayezioro**

### CODE REVIEW

**Comment by chriswmackey** [comment]
Looks good , @ayezioro . Merged!

**Comment by chriswmackey** [comment]
Ah, wait. It looks like I can't easily merge this because I have moved the old component out of WIP and it seems you didn't sync with the master before making these changes. Could you sync with the master and send a new pull request, @ayezioro ?

**Comment by ayezioro** [comment]
@chriswmackey 
I sent a new pull request.
Don't know but always, for me, it is like being in labor ... :-)
Hopefully i'll succeed this time.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I'm sorry but I think I made it worse.  This is my fault and I should have just done conflict resolution via command line when you had originally sent this.  The new request is technically merge-able but it's showing all of these changes that I'm worried that there might be edits that I am not easily able to find in there: https://github.com/mostaphaRoudsari/ladybug/pull/430/files.
I think it's best that I just commit this one using your changed file here.  Give me a second to commit it and then we can close out the pull request.

**Comment by chriswmackey** [comment]
I think what made it worse was that you seem to have deleted the original repository where this pull request came from so I could no longer perform conflict resolution on it.  Ideally, I would have like to have merged this one in over the other because it has the correct commit log.  In the future, I'll just perform conflict resolution when we get a case like this again.  For the sake of keeping everything synced in the future, it might be a good idea now to start a fresh branch that you can keep synced with the master.

In any case, I included all of your changes here:
https://github.com/mostaphaRoudsari/ladybug/commit/21d8b0de2558a47f7147523ec778f78deeb5fa3c

This pull request can be closed and thanks for the bug fixes @ayezioro !

**Pull request closed without merging**
