### PR TITLE
Easter egg in Ladybug greeting & Chrome browser for EPW map

### PR DESCRIPTION
**Pull request by devngc**
Making it a shade more friendly. [Sample](https://github.com/devngc/Work-in-Progress/blob/master/greetings.gh)

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Hi @devngc, I like this approach and the very early versions of Ladybug component used to give you messages like: "it's after midnight! go to bed" and so on. It never made it to the first release as I felt it might be too much. Let's see what other people think about this PR.
@chriswmackey, @ayezioro, @saeranv and everybody else who is watching this repository. Let us know your thought.

**Comment by ayezioro** [comment]
Hi, 
Looks like @devngc is having good time with this (doesn't matter if it is weekend and after hours :-)).
I'm not a fan of the greetings very much but also i don't don't like it.
Personally i don't look much at this output. Only when i want to be sure where the default folder is.
The greeting messages are not going to take much attention. In the worst case you can get a rewarding smile.
Just to be positive with @devngc 's work i'll take it.
Thanks,
-A.

**Comment by devngc** [comment]
Thank you both for sharing you views. Yes, it's a Sunday, I was doing looking at the time module and I thought I could add something like this so I quickly did. Indeed the greeting doesn't get much attention. But I knew that this PR was going to get a lot of attention. Not my intention though.  :joy:

**Comment by saeranv** [comment]
Hah, I remember back during one of the earliest Ladybug release when it would greet you by your name based on a search through the computer's directory structure. I was a TA for a design studio that year, and had to help install Ladybug on every single fourth year student's laptop. I remember the students were always shocked that the plugin could identify who they were. 

Anyway, I think I share your sense of humour @devngc. I feel like a message like "Looks like you're burning the midnight oil. Make sure to recover later!" is a cool easter egg. Personally, I would get rid of a separate message for every time period, and just having one message as an easter egg for those people working past midnight. More than that gets redundant!

**Comment by chriswmackey** [comment]
Sorry for being so late here. As someone who has gotten a lot of enjoyment out of finding random funny lines in the comments Mostapha left, I am generally in the favor of easter eggs hidden in any software, be it a video game or environmental design software. I definitely agree with @saeranv 's comments that Easter eggs are better when they are rare to come by. If it comes all of the time, it seems a  bit less special and, in a worst-case scenario, you can end up being a bit like the Microsoft paperclip (constantly telling people extra info).  So a single egg for someone using it late at night would be nice.

My only other comment would be to make the Easter egg somehow related to Ladybug. In other words, make it a greeting that is unique to environmental design software. Maybe something like:

"Looks like you're working late. You currently have solar access of 0."

Or

"Looks like you're working late. Be sure to reset your circadian rhythm later!"

**Comment by mostaphaRoudsari** [comment]
Thank you everyone for your comments! @devngc I think the conclusion is that it's a good idea to have it but we should make it to be more like an "Easter egg"

**Comment by mostaphaRoudsari** [comment]
Hi @devngc, Thank you for the updates. I'm afraid that we have a conflict now. It's a binary file and should be easy to fix. @chriswmackey just made a change in Ladybug_Ladybug component which should be the reason. Can you include the most recent changes and update this?

**Comment by devngc** [comment]
Sure @mostaphaRoudsari,
Created a fresh PR

**Pull request closed without merging**
