### PR TITLE
Fixing bugs with new Ladybug Photovoltaics components, adding Jason as Contributor and editing the License file

### PR DESCRIPTION
**Pull request by stgeorges**
Hi @chriswmackey , @mostaphaRoudsari ,

Can this pull request be merged please?
It fixes some of the just noticed bugs with the newest "Import Sandia/CEC Photovoltaics Module" components.
Adds ```Jason Sensibaugh``` as Ladybug Contributor, and removes some of the leftovers in Ladybug License file related with the usage of previous Ladybug "Terrain Generator 2" component.

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Thanks @stgeorges!

**Comment by stgeorges** [comment]
Thank you again for the supper quick merge Mostapha!!

**Comment by chriswmackey** [comment]
Looks great @stgeorges !  Thanks, as always!

**Comment by stgeorges** [comment]
Thank you Chris!!

**Pull request merged**
