### PR TITLE
Fixed Small Bug in Solar Adjusted Temperature component

### PR DESCRIPTION
**Pull request by AntonelloDN**

### CODE REVIEW

**Comment by AntonelloDN** [comment]
for some more details read this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1490551&xg_source=msg

Best
Antonello

**Comment by chriswmackey** [comment]
@AntonelloDN ,

Thanks for taking care of this.  It will definitely solve the problem and so I will merge it in.

My only comment is that it could have been written a bit more simply with 2 lines of code like so (since we are already doing a check to make sure that the list has a length of 1):
moveTransform = rc.Geometry.Transform.Translation(bodyLocation_[0].X, bodyLocation_[0].Y, bodyLocation_[0].Z)
mannequinMesh.Transform(moveTransform)

Thanks again,
-Chris

**Comment by AntonelloDN** [comment]
@chriswmackey 

Oh, it is true! thanks Chris.

I have a small suggestion for your component, What do you think to also change bodyposture from item  access into list access. The list of bodypostures should be used when you go on with the simplified method.
In this way, for example, if I have to do some analysis of a terminal of bus, I can check at the same time: sitting areas, restaurant points, queue areas for tickets ... and thus I will have bodyposture: [1, 1, 0]. If I don't want this, you can input a single integer number which will be copied for the lengh of the list of points. And if you go ahead with accurate method (cumskymtx) you take just the first value or you can use a balloon message to say to insert just one value, as now the component does with a list of points.

Best
Antonello

**Comment by chriswmackey** [comment]
@AntonelloDN ,
I agree with the proposal to change body posture to a list value if you would like to implement it.  In the meantime, you should be able to run the type of analysis that you are thinking about by grafting the bodyLocation and bodyPosture inputs before sending them into the component.  The only downside of this approach is that it runs the checkInputs() function each time for each point, which will add an extra second of runtime for each point that is input.  This really adds up when you have a hundreds points like I have in the example I posted on the GH page and is the reason why I changed the location input to list access.
-Chris

**Pull request merged**
