### PR TITLE
Adding solar time hourly sun position points to Ladybug_ladybug component and its consequence in Sun_Path component

### PR DESCRIPTION
**Pull request by stgeorges**

### CODE REVIEW

**Comment by chriswmackey** [comment]
@stgeorges ,
This is awesome!! Thank you for doing this.
I remember one of my peers and LB developer, Trygve, saying that he found solar time much easier to work with and understand than real time that produced figure-8 lamellas.
I would merge the request but I cannot tell if your commits include the altered user objects or just changed source PY code.  I am also having a bit of difficulty understanding what exactly has changed in the component outputs.  Could you include a link to an example GH file with your changes so that I can be sure of what is going on?
-Chris

**Comment by stgeorges** [comment]
Hi @chriswmackey 
I always only commit .py files, I can't commit .ghusers, due to inability to install the github windows application (requires Windows XP >). In most cases I post a link to a .ghuser file as a comment in pull request. Now I didn't do that, as I did not know if you would accept this solution.
Here is the .gh file with both Ladybug_Ladybug and Ladybug_SunPath components changed, as per these two commits: http://www.filedropper.com/hourlysolarpositions
Basically nothing changes that much, I edited the Sunpath.drawSunPath() method from "Ladybug_ladybug" file so that it returns hourly solar time positions too (besides current monthlyCrvs and hourly standard time sun curves). One can now generate hourly solar time curves from those positions easy by interpolating a curve from these positions (crv = rc.Geometry.Curve.CreateInterpolatedCurve(sunPsolarTime, 3, knotStyle)).

The Ladybug_SunPath component virtually does what it did up until now, no changes in its ouputs.
I though that maybe someone else could later add a new input to Ladybug_SunPath component: "solar/standard time" and then based on the value of this input, solar or standard hourly curves will be outputted. But I guess this will require some further editing of the whole SunPath component, which I am not ready to do at the moment.
My only intention for now is to call the Sunpath.drawSunPath() method from "Ladybug_ladybug" component and obtain these hourly solar time positions for PVWatts shading component. That's it.

**Comment by chriswmackey** [comment]
@stgeorges ,
Thanks for the clarification all around.  I checked your file and this solution seems good.  As such, I am going to merge it in.  I know the sunpath well enough to implement an option for solar time and I will try to do this quickly today.
Thanks again for doing this.
-Chris

**Comment by chriswmackey** [comment]
@stgeorges ,
I have finished putting in an option for a solar time display of the sunpath (https://github.com/mostaphaRoudsari/ladybug/commit/32d77dc351a8f4b13c2f86d9f44c35152c017bae).  While the solar time curves are generating correctly, the position of the sun is still based on an input of standard time.  Let's try to implement this in the future (https://github.com/mostaphaRoudsari/ladybug/issues/141) and this is great for the time being.  I can take care of the issue but I have left it unassigned for the time being in case you want to take it on.
-Chris

**Comment by stgeorges** [comment]
@chriswmackey 
Thanks for the quick merge and additions Chris. It looks great!
I would leave the issue on positions of the sun being corrected for solar time to you, if you do not mind.

**Pull request merged**
