### PR TITLE
MonthlyChart Enhancement

### PR DESCRIPTION
**Pull request by devngc**
Legend for comfort chart is provided for coloring purposes whenever a comfort model is called for. 

Please find sample file [here.](https://github.com/devngc/Work-in-Progress/blob/master/WIP/MonthlyBarChart.gh)

Following image displays the added legend for the comfort model;
monthlychart

### CODE REVIEW

**Comment by chriswmackey** [comment]
@devngc ,

Sorry for taking so long to look this over.  I had just moved to a new apartment over the last few weeks but I should have plenty of Ladybug time now :)

I like the change that you are making and thank you for adding it.  The only issue is that, when I plot two data sets together, your new comfort legend appears on top of the current one like so:
image
Here's a file that reproduces the situation:
https://www.dropbox.com/s/dbopzcd5olfphas/MonthlyBarChart_CWM.gh?dl=0

If you could fix this, in a new commit, I will absolutely merge this in.  Thanks again for committing it!
-Chris

**Comment by devngc** [comment]
Hi @chriswmackey,
Thank you for the review. Will surely look into it.
Thank you!
-Devang

**Comment by chriswmackey** [comment]
Thanks, @devngc ,
I think it may be easiest to correct the issue by simply appending the comfort legend to the list that is used to generate the legend.  Secifically, I think this is the `allText `list here:
https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Monthly%20Bar%20Chart.py#L648
and you will have to add 1 to the length of `separatedLists `that is used to generate the legend colors:
https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Monthly%20Bar%20Chart.py#L659

**Comment by devngc** [comment]
Hi @chriswmackey,

Sincerely regret the delay in fixing the legend. Thank you for pointing out the problem with my implementation of comfort legend. I have addressed the same in the latest commit. You may please find the file for review at [this](https://github.com/devngc/Work-in-Progress/blob/master/WIP/MonthlyBarChart.gh) location.

Thanks a lot!
-Devang

**Comment by chriswmackey** [comment]
@devngc ,
This looks absolutely wonderful.  Thank you for taking the time to add this useful feature and fix it .
Merged!

**Comment by devngc** [comment]
Thank you @chriswmackey!

**Pull request merged**
