### PR TITLE
adding new "Terrain analysis" and "Flow paths" components

### PR DESCRIPTION
**Pull request by stgeorges**
Hi @chriswmackey , @mostaphaRoudsari 

Can these two new components be merged?
A preview of both with an example file is given in [this post on the forum](http://www.grasshopper3d.com/group/ladybug/forum/topics/lb-terrain-generator?commentId=2985220%3AComment%3A1608763&groupId=2985220%3AGroup%3A658987).

The pull request also fixes some small issues with the "Terrain Generator 2" component.

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
Beautiful! I think at some point we should have a discussion about the new site components, and the best way to organize them in Ladybug ecosystem.

we = @stgeorges, @AntonelloDN, @chriswmackey

**Comment by chriswmackey** [comment]
Absolutely amazing stuff, @stgeorges !
We should definitely have a conversation soon about the best place for the components in the Ladybug ecosystem.

**Comment by stgeorges** [comment]
Ok. Thank you guys.

**Comment by AntonelloDN** [comment]
amazing and useful stuff! @stgeorges
@mostaphaRoudsari @chriswmackey  I think a new tab for terrain components should be a good solution. 

Guys, any comments and suggestion about my components will be appreciated.

**Pull request merged**
