### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Vyrwn**
Pull request for set Rhino sun component

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@Vyrwn thanks! You should have synced with the master branch before sending a PR. There is a number of conflicts and you're overwriting  the recent changes in Honeybee. Cheers!

**Comment by chriswmackey** [comment]
@Vyrwn ,

Thanks for sending this.  Given the high number of conflicts, I think that it is probably best to close this pull request and have you send a new one.  I think the best way to do it is to completely overwrite your branch right now with the current master code and then add your new userboject from a GH file.

-Chris

**Comment by Vyrwn** [comment]
@mostaphaRoudsari @chriswmackey ,

that is weird because I cloned the master folder and then replaced it into my branch and I just updated that one component. 

I will try it again through the web interface. maybe something went wrong with the PC client. 

-Byron

**Comment by devngc** [comment]
@Vyrwn,
If nothing helps. Re-fork.
Cheers!

**Comment by Vyrwn** [comment]
@devngc ,
thanks for the tip. I will try later today and see what happens

**Pull request closed without merging**
