### PR TITLE
Adding "average sex" input to PET

### PR DESCRIPTION
**Pull request by stgeorges**
Hi @chriswmackey , @mostaphaRoudsari 

Adding "average sex" input to ladybug_ladybug.py physiologicalEquivalentTemperature class, as per request by Chris:
https://github.com/mostaphaRoudsari/ladybug/issues/217#issuecomment-277491317

### CODE REVIEW

**Comment by mostaphaRoudsari** [comment]
@stgeorges thanks! can you get the versions and the dates fixed? As you know we have just updated all the new components with a new version and updated the header license to 2013-2017.

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari ,

Ahh, I oversaw that. I apologize !!
Is it possible that you merge this pull request, and then I will instantly send another one with both "Body Characteristics" and "Thermal Comfort Indices" components versions and 2013-2017 dates fixed?
It's easier like that for me, as I do not want to get stuck with some "this branch has conflict and can not be merged" message.

My apology once again.

**Comment by mostaphaRoudsari** [comment]
Technically you can just fix it and send a new one and there won't be any conflicts but if that makes you feel better then here you go! It won't break anything :) Looking forward to the next PR.

**Comment by stgeorges** [comment]
It does make me feel better!!
I had similar issue at the end of last year. I have no idea why after editing my pull request, the "branch has a conflict" message appeared. It didn't go away even after you send me a pull request.
Maybe I did something wrong that time, it would not happen this time, but thank you for making it easier for me!

**Comment by stgeorges** [comment]
Hi @mostaphaRoudsari ,
Here is the new pull request:
https://github.com/mostaphaRoudsari/ladybug/pull/353

**Pull request merged**
