### PR TITLE
Fix the bug for parallel meshing breps

### PR DESCRIPTION
**Pull request by vincentfs**
Hi Mostapha,

I fixed a few lines in the function parallel_makeSurfaceMesh() and parallel_makeContextMesh(). It can now run in multi-thread successfully. Hope this can be merged into the master repo.

Best,
Vincent

### CODE REVIEW

**Comment by chriswmackey** [comment]
@vincentfs ,
Thank you for cleaning up this function and I like what you are doing here.  My only major comment is that the default to run parallel should not be set to "True" because I know that this function is called by the components that new users are likely to run and it's far safer to have people run their first analysis on a single processor.  As such, this function should follow the _parallel boolean that appears on the ladybug components so that people have to set it manually.
I'll merge the commit in now because I don't want to have this get lost behind other edits but I'm going to change the default to be "False" and it would be great if you could edit the three analysis components to send the _parallel boolean into this function.  After this, send another pull request and I'll merge ti in.
Thanks again!
-Chris

**Comment by chriswmackey** [comment]
Also, for future reference, please remember to change the date any time that you make a change to a component.

**Comment by chriswmackey** [comment]
... and remember to commit the user object as well as the updated .py script following @mostaphaRoudsari 's videos here:
https://www.youtube.com/playlist?list=PLkjfDmSc5Orxq-f_fbmu_HV4tE2ZPIdaC

**Comment by chriswmackey** [comment]
Ok.  I set the default to False, changed the date and committed the userObject:
https://github.com/mostaphaRoudsari/ladybug/commit/b1857941619c78001653143bde421e78b08d58b8

**Comment by mostaphaRoudsari** [comment]
Thanks you @vincentfs and @chriswmackey!

**Comment by vincentfs** [comment]
@chriswmackey Thanks. I will remember to update userObject as well next time!

**Pull request merged**
