### PR TITLE
2 more Outputs added

### PR DESCRIPTION
**Pull request by devngc**
1. windSpeeds (Parsed wind speeds)
2. windDirections (Parsed wind directions) are provided as output from the component.

### CODE REVIEW

**Comment by devngc** [comment]
@mostaphaRoudsari, I am working on a small component for Ladybug, for which I need wind speeds and wind directions. Therefore, I thought of using the parsing capabilities of this component itself.

**Comment by mostaphaRoudsari** [comment]
@devngc can you help me to understand your intention? What are you exactly trying to achieve? I wonder if it's already available in some other ways.

**Comment by devngc** [comment]
@mostaphaRoudsari OK. I intend to get the the wind speeds and the wind directions for the wind rose that is being displayed. Therefore, the wind speeds and the wind directions must be parsed in response to the conditional statement and / or analysis period that user might connect. That's what I have done. Taking this output, I intend to make a component that prepares a bit different visualization of that data.

**Comment by mostaphaRoudsari** [comment]
Hi @devngc. Sounds good. I suggest opening an issue for the new component before going further with the development, so we all know what to expect. Thanks.

**Comment by devngc** [comment]
@mostaphaRoudsari, Thank you! No problem. I can do that.

**Comment by chriswmackey** [comment]
@devngc ,
Sorry for being late to respond and I just wanted to say that the edit looks good.  Keep up the good work and, as @mostaphaRoudsari says, letting us know beforehand that you're working on something will help ensure that we don't work on the same issues/components at the same time
-Chris

**Comment by devngc** [comment]
@chriswmackey,
Appreciate the words of encouragement. Thank you! I will surely raise the issue soon about the component I have in mind.

**Pull request merged**
